### ISSUE TITLE
1.0.3.4使用默认的MsgPacket向客户端返回实体信息报错

### ISSUE THREAD

**Issue by e4ky** [IKende/XRPC#26]
nuget中1.0.3.4版本，使用默认的**MsgPacket**向客户端返回实体信息报错，指定**JsonPacket**后，问题解决，看日志像是实体类的内容还是被JSON序列华后没处理"号。

报错内容：

> [20:50:02] [Debug] [10000004][::ffff:127.0.0.1]:54703 send event data:{"ID":10000004,"EventPath":null,"Properties":{},"Data":[{"ReportID":2,"UserID":"123456","DeviceID":"4569356885","ReportDate":"2020-09-13T20:50:02.4845313+08:00","HeartRate":98.0,"BreatheRate":15.0,"Remark":null}],"EventError":200,"ResponseTime":0.0,"Token":null}
[20:50:02] [Error] Next queue process EventNext.EventActionHandlerContext error Write protocol data error Failed to serialize BCGChair.Model.ReportInfo value.@   at BeetleX.XRPC.RPCPacket.Write(Options rpcOption, PipeStream stream)
   at BeetleX.XRPC.Packets.ServerPacket.OnEncode(ISession session, Object data, Stream stream)
   at BeetleX.XRPC.Packets.ServerPacket.Encode(Object data, ISession session, Stream stream)
   at BeetleX.TcpSession.WriterData(Object data, Stream stream)
   at BeetleX.TcpSession.ProcessSendMessages()
   at BeetleX.TcpSession.Send(Object data)
   at BeetleX.XRPC.XRPCServer.OnResponse(RPCPacket request, RPCPacket response)
   at BeetleX.XRPC.XRPCServer.EventCompleted.Completed(IEventOutput data)
   at EventNext.EventActionHandlerContext.Execute()
   at EventNext.NextQueue.OnStart(Object state)

传输的实体类结构
```
public class ReportInfo

 {

        public int ReportID { set; get; }

        public string UserID { set; get; }

        public string DeviceID { set; get; }

        public DateTime ReportDate { set; get; }

        public double HeartRate { set; get; }

        public double BreatheRate { set; get; }

        public string Remark { set; get; }

}
```

**Comment by IKende** [comment]
MsgPacket消息需要打上key标签才行

**Comment by e4ky** [comment]
果然，参考https://github.com/neuecc/MessagePack-CSharp配置好后就解决了。
