### ISSUE TITLE
运行一段时间后，服务器端不响应客户端请求，但可以telnet到

### ISSUE THREAD

**Issue by zzeric** [IKende/XRPC#36]
只能重启程序。
已经开启ServerGC，内存没有泄漏，session数量也只是增长到200多

服务器版本用的是nuget上的1.2.0.1802

**Comment by zzeric** [comment]
暂时估计是互联网上扫描或者爬虫连接后会除非decode error，累计一定次数后就会失去响应，可以通过循环curl复现。
[23:27:03] [Error] session [::ffff:116.7.22.35]:33914@24 error session buffer decoding error! @The message to long!
   at BeetleX.XRPC.RPCPacket.Read(Options rpcOption, PipeStream stream)
   at BeetleX.XRPC.Packets.ServerPacket.Decode(ISession session, Stream stream)
   at BeetleX.TcpServer.SessionReceive(SessionReceiveEventArgs e)

**Comment by beetlex-io** [comment]
如果并发不高的情况下可以开启debug日志看情况，建议不要在使用过程使用Task.wait这样的方法

**Comment by zzeric** [comment]
可能是操作系统的原因，部署到linux下就没出现了。
